[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "helloapp"
version = "0.1.0"
description = "Simple greeting application"
authors = [{ name = "Codex" }]
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
helloapp = "helloapp.cli:main"

[project.optional-dependencies]
ui = ["streamlit>=1.0"]
